version: "3.5"

services:
  calibre-server:
    build: .
    ports:
      - "8081:8081"  # Port for Calibre server
    volumes:
      - /home/oldenburg/library:/opt/library  # Map the host folder to the container
