version: "3.5"

services:
  calibre-server:
    build: .
    ports:
      - "8081:8081"  # Port for Calibre server
    volumes:
      - /path/to/host/library:/opt/library  # Map the library folder to the host
